on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm install clang-format@1.8.0

      - run: |
          npx clang-format --dry-run --Werror $(find . -name '*.js')
